# rcnn-fer Docker Makefile
PROGRAM="RCNN-FER"

CPU_REGISTRY_URL=so77id
GPU_REGISTRY_URL=so77id
CPU_VERSION=latest
GPU_VERSION=latest
CPU_DOCKER_IMAGE=tensorflow-opencv-cpu-py3
GPU_DOCKER_IMAGE=tensorflow-opencv-gpu-py3

